add_newline = false
format = """$directory$character"""
right_format = """$all"""
command_timeout = 1000

[character]
disabled = true

[git_branch]
symbol = "ï˜ "
format = '[$symbol$branch]($style) '
style = 'bold dimmed white'

[git_status]
format = '[$all_status$ahead_behind]($style) '
style = 'bold dimmed white'
conflicted = 'ğŸ³'
up_to_date = ''
untracked = 'ó±™ƒ '
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'
stashed = 'ï£– '
modified = 'ï„ '
staged = '[++\($count\)](green)'
renamed = 'ïª¶ '
deleted = 'ï€” '

[aws]
format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style)'
disabled = true
style = 'bold dimmed white'
symbol = "îŒ½ "

[bun]
format = '[bun ($version )]($style)'
disabled = false
version_format = 'v${raw}'
style = 'bold dimmed white'

[docker_context]
format = '[$symbol$context âœ“]($style) '
only_with_files = false
symbol = "î™ "
style = "bold dimmed white"

[golang]
format = '[$symbol($version )]($style)'
symbol = 'î™ '
style = 'bold dimmed white'

[hostname]
disabled = false
ssh_only = true
format = 'on [$hostname]($style)'
ssh_symbol = "î¬ "
style = "bold dimmed white"

[lua]
format = '[$symbol($version )]($style)'
symbol = "î˜  "
style = "bold dimmed white"
disabled = true

[rust]
# format = '[$symbol($version )]($style)'
format = '[rust ($version )]($style)'
symbol = "î¨ "
style = "bold dimmed white"

[package]
disabled = true

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = "î˜† "
pyenv_version_name = false
style = 'bold dimmed white'

[terraform]
format = '[ó±¢ $workspace]($style) '

[nodejs]
format = '[$symbol($version )]($style)'
style = 'bold dimmed white'

[cmd_duration]
disabled = true
